from need_this.models import Zodiac
z = Zodiac(sign="Capricorn", value=1)
z.save()
z = Zodiac(sign="Aquarius", value=2)
z.save()
z = Zodiac(sign="Pisces", value=3)
z.save()
z = Zodiac(sign="Aries", value=4)
z.save()
z = Zodiac(sign="Taurus", value=5)
z.save()
z = Zodiac(sign="Gemini", value=6)
z.save()
z = Zodiac(sign="Cancer", value=7)
z.save()
z = Zodiac(sign="Leo", value=8)
z.save()
z = Zodiac(sign="Virgo", value=9)
z.save()
z = Zodiac(sign="Libra", value=10)
z.save()
z = Zodiac(sign="Scorpio", value=11)
z.save()
z = Zodiac(sign="Sagitarrius", value=12)
z.save()