"""
Django settings for biscuits project.

Generated by 'django-admin startproject' using Django 1.11.29.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6yvzw+6saple0r3y=^f0b+%o73sgi@wo8(l=gzw$44j84asqa$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['starastrology.org', '3.139.91.10']


# Application definition

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'astro',
    'need_this.apps.NeedThisConfig',
    'django.contrib.staticfiles'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    #'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
DATABASES = {
       'default': {
           'ENGINE': 'djongo',
           'NAME': 'astrology',
       }
   }


ROOT_URLCONF = 'biscuits.urls'

WSGI_APPLICATION = 'biscuits.wsgi.application'

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    '/var/www/html/StarAstrology/biscuits/static/',
]
STATIC_ROOT = '/var/www/html/StarAstrology/static/'
